### PR TITLE
Fix compile error under macOS Big Sur

### PR DESCRIPTION
**Pull request by Bo98**
The implicit function declaration warning is now an error in macOS Big Sur. As such, rdiscount 2.2.0.1 fails to install under the OS.

```
rdiscount.c:53:17: error: implicit declaration of function
'rb_rdiscount__get_flags' is invalid in C99
[-Werror,-Wimplicit-function-declaration]
    int flags = rb_rdiscount__get_flags(self);
                ^
rdiscount.c:96:17: error: implicit declaration of function
'rb_rdiscount__get_flags' is invalid in C99
[-Werror,-Wimplicit-function-declaration]
    int flags = rb_rdiscount__get_flags(self);
                ^
```

The fix is to simply move the function definition to be before it is used.

### CODE REVIEW

**Comment by davidfstr** [comment]
Change looks safe enough.

I’ll need to investigate a bit to see why the Travis build failed on an old Ruby version.

**Comment by pcr910303** [comment]
@davidfstr May I ask to make a new release if possible? It would be great if I can use the new version...

**Comment by davidfstr** [comment]
@pcr910303 I will plan to make a release this weekend.

**Comment by davidfstr** [comment]
RDiscount 2.2.0.2 is now released with this issue merged.

**Pull request merged**
