### PR TITLE
Feature/modernize

### PR DESCRIPTION
**Pull request by fliiiix**
I still use this gem is there any interest into bringing this up to ruby 3 and update discount and maybe build and test with github actions instead of an awkward combination of travis and appveyor?

I would be willing to spend some time on that if there is interest and my stuff gets reviewed and merged and eventual released. 

todo:
- [x] conformance:1.0 test: Markdown Documentation - Syntax ...
- [x] github action linux
- [x] github action windows
- [x] readme badges for CI
- [x] investigate if everything from here is done ok enough https://github.com/davidfstr/rdiscount/issues/148
- [x] run a real-world test of this

### CODE REVIEW

**Comment by davidfstr** [comment]
I don't personally have bandwidth to make or review major changes to this gem over the next year or so (2022). Lot of major life changes coming up.

Really I think the gem probably needs a new maintainer, especially someone who works with Ruby (and preferably also some C) on a regular basis. These days I'm usually working with Python and JavaScript but almost never in Ruby.

Perhaps you'd be interested in stepping up to take up a maintainer-style role?

**Comment by fliiiix** [comment]
I can try, no promises that i do the best job but better than unmaintained i guess

**Comment by davidfstr** [comment]
I’ve given you collaborator access, so you should be able to make direct changes now.

**Comment by fliiiix** [comment]
@davidfstr how do you want to handle releasing? 

I would tag the release commit and merge it to master, then someone needs to upload it to rubygems.org my handle is `l33tname` if you want me to do that

**Comment by davidfstr** [comment]
@fliiiix I did verify the build, tag the commit, merge to master, and push to RubyGems.

Thanks for taking the time to do the heavy lifting to upgrade this gem!

I hope you (and others) will continue to help maintain RDiscount, at least while my life continues to be crazy.

**Pull request merged**
